name       : perl-data-compare
version    : '1.27'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/D/DC/DCANTRELL/Data-Compare-1.27.tar.gz : 818a20f1f38f74e65253cf8bcf6fed7f94a5a8dd662f75330dcaf4b117cee8bd
license    : GPL-2.0
component  : programming.perl
summary    : This module compares arbitrary data structures to see if they are copies of each other.
description: |
    This module compares arbitrary data structures to see if they are copies of each other.
rundeps    :
    - perl-file-find-rule
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
