name       : perl-data-compare
version    : 1.25
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DC/DCANTRELL/Data-Compare-1.25.tar.gz : 1d4b36db545fa9fbacd8c012618f6a7846238ee12ab627a2764cfaf45ad4ea73
license    : GPL-2.0
component  : programming.perl
summary    : This module compares arbitrary data structures to see if they are copies
    of each other.
description: |
    This module compares arbitrary data structures to see if they are copies of each other.
rundeps    :
    - perl-file-find-rule
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
